### ISSUE TITLE
Duplicate messages

### ISSUE THREAD

**Issue by kieulam141** [Graylog2/graylog-plugin-mongodb-profiler#11]
I setup this plugin in our graylog system successfully.
But i got 1 bug.Our graylog received duplicate messages with the same content.
Here is my capture: http://prnt.sc/f1dyc5

**Comment by joschi** [comment]
@kieulam141 Are you running the input twice?

**Comment by kieulam141** [comment]
Oh, I checked it.I used global input and I have 2 graylog nodes.So I have 2 the same messages in 2 nodes.
