### ISSUE TITLE
No data getting populated in ES

### ISSUE THREAD

**Issue by anirudhkkw** [Graylog2/graylog-plugin-mongodb-profiler#5]
No data is getting populated in elasticsearch. The inputs say it's running.

**Comment by joschi** [comment]
@anirudhkkw Which version of the plugin are you running? Which version of Graylog are you running?

**Comment by anirudhkkw** [comment]
Graylog 2.0.0-rc.1 (f098ffa)
plugin 1.0.1

**Comment by joschi** [comment]
@anirudhkkw We haven't tested the compatibility of this plugin with Graylog 2.0.0 yet, so it might as well not work with that version.

I'll leave this issue open until we've checked that.

**Comment by joschi** [comment]
@anirudhkkw We've released a new version of the plugin which is compatible with Graylog 2.0.0: https://github.com/Graylog2/graylog-plugin-mongodb-profiler/releases/tag/2.0.1
